eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: 'true'

spring:
  application:
    name: CLOUD-CONFIG-SERVER

  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:cloudConfigServerDB

  h2:
    console:
      path: /h2-console
      enabled: 'true'

  jpa:
    show-sql: 'true'

  cloud:
    config:
      server:
        git:
          uri: https://github.com/regithkumarc/cloud-config-server

server:
  port: '8084'
