create table PRODUCT_DETAILS (
    PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(100),
    PRODUCT_CATEGORY VARCHAR(100),
    PRODUCT_PRICE INT
)

INSERT INTO PRODUCT_DETAILS VALUES (1,'Samsung s22','Mobile',1500);
INSERT INTO PRODUCT_DETAILS VALUES (2,'Samsung Tab','Tablet',1000);
INSERT INTO PRODUCT_DETAILS VALUES (3,'Nikon sD700','Camera',700);
INSERT INTO PRODUCT_DETAILS VALUES (4,'Samsung Crystal','Tv',500);
INSERT INTO PRODUCT_DETAILS VALUES (5,'Yonex Batminten','Sports',100);