spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order/**
                - Method=GET,POST,PUT,DELETE
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment/**
                - Method=GET,POST,PUT,DELETE

  main:
    web-application-type: reactive

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
