spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:paymentServiceDB

  h2:
    console:
      path: /h2-console
      enabled: 'true'

  jpa:
    show-sql: 'true'

server:
  port: '8082'
