//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.20 at 07:42:35 PM IST 
//


package com.example.soapwebservice.employees;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.soapwebservice.employees package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soapwebservice.employees
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetEmployeesByIdRequest }
     * 
     */
    public GetEmployeesByIdRequest createGetEmployeesByIdRequest() {
        return new GetEmployeesByIdRequest();
    }

    /**
     * Create an instance of {@link UpdateEmployeesRequest }
     * 
     */
    public UpdateEmployeesRequest createUpdateEmployeesRequest() {
        return new UpdateEmployeesRequest();
    }

    /**
     * Create an instance of {@link GetAllEmployeesRequest }
     * 
     */
    public GetAllEmployeesRequest createGetAllEmployeesRequest() {
        return new GetAllEmployeesRequest();
    }

    /**
     * Create an instance of {@link AddEmployeesRequest }
     * 
     */
    public AddEmployeesRequest createAddEmployeesRequest() {
        return new AddEmployeesRequest();
    }

    /**
     * Create an instance of {@link UpdateEmployeesResponse }
     * 
     */
    public UpdateEmployeesResponse createUpdateEmployeesResponse() {
        return new UpdateEmployeesResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link EmployeesInfo }
     * 
     */
    public EmployeesInfo createEmployeesInfo() {
        return new EmployeesInfo();
    }

    /**
     * Create an instance of {@link DeleteEmployeesRequest }
     * 
     */
    public DeleteEmployeesRequest createDeleteEmployeesRequest() {
        return new DeleteEmployeesRequest();
    }

    /**
     * Create an instance of {@link GetAllEmployeesResponse }
     * 
     */
    public GetAllEmployeesResponse createGetAllEmployeesResponse() {
        return new GetAllEmployeesResponse();
    }

    /**
     * Create an instance of {@link GetEmployeesByIdResponse }
     * 
     */
    public GetEmployeesByIdResponse createGetEmployeesByIdResponse() {
        return new GetEmployeesByIdResponse();
    }

    /**
     * Create an instance of {@link AddEmployeesResponse }
     * 
     */
    public AddEmployeesResponse createAddEmployeesResponse() {
        return new AddEmployeesResponse();
    }

    /**
     * Create an instance of {@link DeleteEmployeesResponse }
     * 
     */
    public DeleteEmployeesResponse createDeleteEmployeesResponse() {
        return new DeleteEmployeesResponse();
    }

}
