//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.20 at 07:42:35 PM IST 
//


package com.example.soapwebservice.articles;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.soapwebservice.articles package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soapwebservice.articles
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllArticlesRequest }
     * 
     */
    public GetAllArticlesRequest createGetAllArticlesRequest() {
        return new GetAllArticlesRequest();
    }

    /**
     * Create an instance of {@link GetArticlesByIdRequest }
     * 
     */
    public GetArticlesByIdRequest createGetArticlesByIdRequest() {
        return new GetArticlesByIdRequest();
    }

    /**
     * Create an instance of {@link UpdateArticlesResponse }
     * 
     */
    public UpdateArticlesResponse createUpdateArticlesResponse() {
        return new UpdateArticlesResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link ArticlesInfo }
     * 
     */
    public ArticlesInfo createArticlesInfo() {
        return new ArticlesInfo();
    }

    /**
     * Create an instance of {@link AddArticlesResponse }
     * 
     */
    public AddArticlesResponse createAddArticlesResponse() {
        return new AddArticlesResponse();
    }

    /**
     * Create an instance of {@link UpdateArticlesRequest }
     * 
     */
    public UpdateArticlesRequest createUpdateArticlesRequest() {
        return new UpdateArticlesRequest();
    }

    /**
     * Create an instance of {@link DeleteArticlesRequest }
     * 
     */
    public DeleteArticlesRequest createDeleteArticlesRequest() {
        return new DeleteArticlesRequest();
    }

    /**
     * Create an instance of {@link GetArticlesByIdResponse }
     * 
     */
    public GetArticlesByIdResponse createGetArticlesByIdResponse() {
        return new GetArticlesByIdResponse();
    }

    /**
     * Create an instance of {@link AddArticlesRequest }
     * 
     */
    public AddArticlesRequest createAddArticlesRequest() {
        return new AddArticlesRequest();
    }

    /**
     * Create an instance of {@link GetAllArticlesResponse }
     * 
     */
    public GetAllArticlesResponse createGetAllArticlesResponse() {
        return new GetAllArticlesResponse();
    }

    /**
     * Create an instance of {@link DeleteArticlesResponse }
     * 
     */
    public DeleteArticlesResponse createDeleteArticlesResponse() {
        return new DeleteArticlesResponse();
    }

}
