spring:
  application:
    name: FEIGN-STUDENT-SERVICE

  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:feignStudentServiceDB

  h2:
    console:
      path: /h2-console
      enabled: 'true'

  jpa:
    show-sql: 'true'

#  zipkin:
#    base-url: http://localhost:9411/
#
#  sleuth:
#    sampler:
#      probability: 1.0
#
#  web:
#    client:
#      enabled: true

server:
  port: 8087
